server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: never
    include-message: always
    path: /error
    whitelabel:
      enabled: false
  servlet:
    context-path: /v1

management:
  endpoints:
    web:
      exposure:
        include: "info,health,metrics,scheduledtasks,tasque"

springdoc:
  api-docs:
    path: /api-docs

endpoints:
  shutdown:
    enabled: true

spring:
  flyway:
    locations: ${FLYWAY_MIGRATION_PATH}
    validateOnMigrate: 'false'

logging:
  pattern:
    level: "%X{values}"
  level:
    com.lms: ${LOGGING_LEVEL_COM_LMS}

datasource:
  username: ${PG_USER}
  jdbc-url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DB}
  password: ${PG_PASSWORD}

build-info:
  version: 0.1.${BUILD_NUMBER}
  environment: ${RUNTIME_ENVIRONMENT}

domain-web: ${DOMAIN_WEB}

ip-info:
  token: ${IP_INFO_TOKEN}

jwt-secret: ${JWT_SECRET_KEY}